name: Bandit Analysis

on: [push]

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Run Bandit analysis
        run: |
          docker run --rm -v $(pwd):/app hysnsec/bandit bandit -r /app -f json -o /app/bandit-output.json
        continue-on-error: true

      - name: Upload Bandit report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-output.json
