name: Safety Check

on: [push]

jobs:
  safety:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run safety check
        run: |
          docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt json > safety-report.json
        continue-on-error: true

      - name: Upload safety report
        uses: actions/upload-artifact@v4
        with:
          name: safety-report
          path: safety-output.json
        if: always()
